Begin detection operator changes for ERDOS redesign
erdos-project/pylot pull request #230
Opened 2022-03-14 09:22 UTC by objorkman

* Adds `detection_operator_runner.py` to test operator changes
* Update `detection_operator.py` to erdos redesign operator style

2022-03-16 04:31 UTC, pschafhalter commented on pylot/perception/detection/detection_operator.py
> +    def on_left_data(self, context: TwoInOneOutContext, data: Any):
```suggestion
    def on_left_data(self, context: TwoInOneOutContext, data: CameraFrame):
```

2022-03-16 04:31 UTC, pschafhalter commented on pylot/perception/detection/detection_operator.py
> +        #     erdos.WatermarkMessage(erdos.Timestamp(is_top=True)))
Could you delete this? The new version of ERDOS should automatically send top watermarks after `destroy()` finishes running.

2022-03-16 22:21 UTC, pschafhalter approved these changes
LGTM

2022-03-17 00:27 UTC, sukritkalra requested changes
Can you also please add a TODO to remove the `FrameMessage` when we're done with the port?

2022-03-17 00:27 UTC, sukritkalra commented on pylot/perception/detection/detection_operator.py
> +        tf.config.experimental.set_memory_growth(physical_devices[0], True)
Can you please revert this to use the flags?

2022-03-17 06:28 UTC, objorkman commented
Changes made!

2022-03-17 06:59 UTC, pschafhalter commented on detection_operator_runner.py
> +                    # TODO: Remove FrameMessage when redesign port complete
Could you move this todo above the `FrameMessage` class?
https://github.com/erdos-project/pylot/blob/ac024de97025e0afad7f08202950e436cf3aed36/pylot/perception/messages.py#L14

2022-03-17 23:56 UTC, merged