Update traffic light detection operator for redesign
erdos-project/pylot pull request #231
Opened 2022-03-15 09:11 UTC by objorkman

* Add traffic light detector to runner script
* Update `traffic_light_det_operator.py` to redesign
<img width="483" alt="Screen Shot 2022-03-15 at 2 06 12 AM" src="https://user-images.githubusercontent.com/7193442/158344424-f6f14e35-dc89-45ad-9b17-7f1ca750dacd.png">

2022-03-18 00:02 UTC, pschafhalter requested changes
Could you fix the merge conflicts?

2022-03-18 00:02 UTC, pschafhalter commented on pylot/perception/detection/traffic_light_det_operator.py
> +            TrafficLightsMessage(context.timestamp, traffic_lights))
```suggestion
        context.write_stream.send(
            Message(context.timestamp, traffic_lights))
```

2022-03-18 21:07 UTC, pschafhalter commented on pylot/perception/detection/detection_operator.py
> +        tf.config.experimental.set_memory_growth(physical_devices[0], True)
Why were these changes made?

2022-03-19 02:48 UTC, objorkman commented on pylot/perception/detection/detection_operator.py
> +        tf.config.experimental.set_memory_growth(physical_devices[0], True)
Oops, fixed it!

2022-03-19 03:04 UTC, pschafhalter approved these changes
LGTM

2022-03-19 03:04 UTC, merged