[Redesign] Update Simple Logger Operators
erdos-project/pylot pull request #255
Opened 2022-04-28 04:15 UTC by objorkman

* Updates to `BoundingBoxLoggerOperator`, `CameraLoggerOperator`, and `MultipleObjectTrackerOperator`

2022-05-08 06:12 UTC, pschafhalter requested changes

2022-05-08 06:12 UTC, pschafhalter commented on pylot/loggers/bounding_box_logger_operator.py
>                  Received message.
```suggestion
            data: The obstacle to log.
```

2022-05-08 06:12 UTC, pschafhalter commented on pylot/loggers/bounding_box_logger_operator.py
> +    def __init__(self, flags, file_base_name):
```suggestion
    def __init__(self, flags, file_base_name: str):
```

2022-05-08 06:12 UTC, pschafhalter commented on pylot/loggers/camera_logger_operator.py
>          """Invoked whenever a frame message is received on the stream."""
```suggestion
        """Invoked whenever a camera frame is received."""
```

2022-05-08 06:12 UTC, pschafhalter commented on pylot/loggers/multiple_object_tracker_logger_operator.py
>                  Received message.
```suggestion
            data: Received obstacles.
```

2022-05-18 18:13 UTC, objorkman commented
Thanks for the comments - updated!

2022-05-25 23:24 UTC, merged